# -*- coding: utf-8 -*-
"""Day 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VL118f_JkaT2GnNpFdPEEf7adTMGHTbg
"""

d=int(input("Enter number between 0-6: "))
if(d==0):
  print('Sunday')
elif(d==1):
  print("Monday")
elif(d==2):
  print("Tuesday")
elif(d==3):
  print("Wednesday")
elif(d==4):
  print("Thursday")
elif(d==5):
  print("Friday")
elif(d==6):
  print("Saturday")
else:
  print("Invalid input")

for i in range(5):
  for j in range(i+1):
    print("*",end="")
  print("\n")

l=int(input("Enter the limit :"))
for i in range(l):
  for j in range(i+1):
    print("*",end="")
  print("\n")

for i in range(5):
  s=65
  for j in range(i+1): 
    print(chr(s),end="")
    s=s+1
  print("\n")

l=int(input("Enter the limit : "))
for i in range(l):
  n=1
  for j in range(i+1): 
    print(n,"\t",end="")
    n=n+1
  print("\n")

for r in range(6):  
    for c in range(7):  
        if (r==0 and c %3 !=0)or(r==1 and c %3==0) or(r-c==2) or(r+c==8):  
            print("*",end="   ")  
        else:  
            print('',end="   ")  
    print()

for r in range(6):  
    for c in range(7):  
        if (r==0 and c %3 !=0)or(r==1 and c %3==0) or(r-c==2) or(r+c==8):  
            print("*",end="   ")
        elif(r==2 and (r-c !=2) and (r+c!=8)):
            print("A",end="  ")  
        else:  
            print('',end="   ")  
    print()

s="Eeman"
for r in range(6):  
    for c in range(7):  
        if (r==0 and c %3 !=0)or(r==1 and c %3==0) or(r-c==2) or(r+c==8):  
            print("*",end="   ")
        elif(r==2 and c==1):
            print("A",end="  ")  
        elif(r==2 and c==2):
            print("Y",end="  ")  
        elif(r==2 and c==3):
            print("E",end="  ")  
        elif(r==2 and c==4):
            print("S",end="  ")  
        elif(r==2 and c==5):
            print("H",end="  ") 
        else:  
            print('',end="   ")  
    print()

s="Eeman"
for r in range(6):  
    for c in range(7):  
        if (r==0 and c %3 !=0)or(r==1 and c %3==0) or(r-c==2) or(r+c==8):  
            print("*",end="   ")
        elif(r==2 and (r-c !=2) and (r+c!=8)):
          for i in s:
            print(i,end="   ")
            break
        else:  
            print('',end="   ")  
    print()

s="eeman"
for i in s:
            print(i,end="   ")